require "user.plugins"
require "user.settings"
require "user.keymaps"
require "user.nvim-tree"
require "user.treesitter"
-- require "user.gitsigns"
require "user.lualine"
require "user.indentline"
require "user.lsp.init_lsp"
require "user.illuminate"
require "user.cmp"
require "user.bufferline"
